language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
install:
  - pip install --upgrade setuptools pip pytest pytest-cov
  - pip install .
addons:
  sonarcloud:
    organization: "digiklausur"
    token: ${SONAR_TOKEN}
script:
  - py.test --cov nbassignment -v --cov-report xml
  - sonar-scanner