language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
install:
  - pip install --upgrade setuptools pip pytest pytest-cov
  - pip install .
addons:
  sonarcloud:
    organization: "digiklausur"
    token: 
      secure: "7DGPzxXIYAVDSZr1UoIMPVPctKAKrg4aOF8S1EARiczZA+vk9AmGggqhQ0KGReSDQpzwTLbY9aBm7V3Ick8855HwXQ/FOWC/pWfGHCSbSBqA442f/REdXpuzALiL1mCdvpZZwwap4OZxFEZbXnf27EVg/+GWT/mdAL4vwz4TnktiQHizeHAhAXzbSzRqS1+Rq9d52eqDlEIbbGllPy06owLFqqfWaSacQiigVFrM83WvHbs6Ql6PfHH0HdnlwQQp1tYQ/X1eFtUfmiLDPwvHkHVutsaQRGdfWZ+RVoUGTW62E1oOs++aC7xqQMEUJcO1Oq+pQFRiXVN6J3yeq0lantuBIfk/uFOHbu5ts4crzTuEmvv3DAoMoTleNfimqj6ODy4jwYFPk50z8oPNN3bPGn3UPO5h60PBXljB8FNfHo+sSxngG73wrVOg4YUFdbTv0YpfNbWgJfoVlJCxNGI1ADKn47rvzDcv3FSpsgInq4DqPTBxFRu8Hna/+0zChSBVy52skxCsedKNMO2roiNC6cRbZToC+Iea9BTK909eWO1WtbDuQu91t80/342BWk0c6XOGX/waUm8zMkHBKJfFipbbiVfsLcCxzm9D6wZNyU/XldwTe3xoswG9CC64tp03LxSeqCgV+MNHFHSRrLDc6h9uC/0v+Q3RdMlMifYjTAQ="
script:
  - py.test --cov nbassignment -v --cov-report xml
  - sonar-scanner